# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECU',
            fields=[
                ('serial_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=4096)),
                ('cryptography_method', models.CharField(default='ed25519', max_length=16)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VIN', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='ecu',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecus', to='director.Vehicle'),
        ),
    ]
